### PR TITLE
Bazel version bumps

### PR DESCRIPTION
**Pull request by Autumn-Ou**
I saw a warning about needing to stay on an older bazel version but this seems to function perfectly fine on Ubuntu 22.04 & windows 11, I have no way of testing this for MacOS but it shouldn't cause an issue there and I thought it would be better to bump this. This also includes documentation for npm based bazelisk install for all platforms, tends to be a lot more convenient.

### CODE REVIEW

**Comment by camearle20** [comment]
IIRC we only needed this for GitHub Actions because the installed version of Bazel is too old, so this lets us set the exact version. For local development we just use a systemwide install. Any warnings about specific versions are definitely out of date, we need to go through and update a lot of the docs about that at some point.

**Comment by camearle20** [comment]
The main reason for me at least is that Bazelisk does not install the terminal tab completion helpers for Bazel, whereas the local install script does. Also for macOS we still require using the x86 version of Bazel for parts of the build, which wouldn't be installed on an M1 machine by bazelisk. That second issue should be fixed soon, and we have no problem with people using bazelisk if it's working for them, so I'll go ahead and merge this.

**Comment by camearle20** [comment]
I ended up deleting this commit after we merged it in. There are still issues with macOS around gtest being too old to work with Bazel 6 that will make this more involved to update to. Once these are fixed I can merge this in again.

**Comment by camearle20** [comment]
There are a lot of build cleanups and fixes on my radar now that the season is over, and Bazel 6 is definitely one of them, so I should be able to do this pretty soon. Once I fix gtest and friends it might be easiest for you to just open a new PR with these changes so I can merge it again since I had to force push to revert the other commit. I'll comment back here when that's ready

**Comment by Autumn-Ou** [comment]
I'll open a new PR when it's ready set to the newest version of bazel at the time that I can confirm works which should cover all platforms except macOS.

**Pull request merged**
