### PR TITLE
PDP + System Stats Conduit Integration

### PR DESCRIPTION
**Pull request by jlmcmchl**
This PR places PDP info + system stats under conduit / JNI-free calls.

I haven't implemented a means to set the PDP module ID + type, but I'm open to recommendations on how that should be implemented.

Untested on a robot, but it builds and passes existing tests. I have hardware with me if we need to test this on a robot before it's considered OK to merge.

### CODE REVIEW

**Comment by jlmcmchl** [comment]
Ran it locally this weekend after setting up a dev environment for simulation - having some difficulty with adding a dependency to conduit. `wpi::GetStackTrace()` is within wpiutil, but simply adding it to `conduit/wpilibio/BUILD` doesn't seem to work. Any ideas?

Here's the program output when I run simulation:
```bash
jlmcmchl@DESKTOP-PGRFQTU:~/Code/jlmcmchl/pdp-hal-test$ /usr/bin/env HALSIM_EXTENSIONS=/home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release/libhalsim_gui.so: DYLD_LIBRARY_PATH=/home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release LD_LIBRARY_PATH=/home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release /home/jlmcmchl/wpilib/2022/jdk/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:39789 -Djava.library.path=/home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release @/tmp/cp_ewkpl92r3611i2mh4j0csfvin.argfile frc.robot.Main 
HAL Extensions: Attempting to load: libhalsim_gui
Simulator GUI Initializing.
Simulator GUI Initialized!
HAL Extensions: Successfully loaded extension
********** Robot program starting **********
Error at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method): Unhandled exception: java.lang.UnsatisfiedLinkError: /home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release/libwpilibio.so: /home/jlmcmchl/Code/jlmcmchl/pdp-hal-test/build/jni/release/libwpilibio.so: undefined symbol: _ZN3wpi13GetStackTraceEi
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.littletonrobotics.conduit.ConduitJni.<clinit>(ConduitJni.java:11)
        at org.littletonrobotics.conduit.ConduitApi.<init>(ConduitApi.java:40)
        at org.littletonrobotics.conduit.ConduitApi.getInstance(ConduitApi.java:28)
        at org.littletonrobotics.junction.Logger.periodicBeforeUser(Logger.java:175)
        at org.littletonrobotics.junction.LoggedRobot.startCompetition(LoggedRobot.java:85)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:443)
        at java.base/java.lang.Thread.run(Thread.java:829)

Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:388): The robot program quit unexpectedly. This is usually due to a code error.
  The above stacktrace can help determine where the error occurred.
  See https://wpilib.org/stacktrace for more information.
Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:395): The startCompetition() method (or methods called by it) should have handled the exception above.
```

**Comment by camearle20** [comment]
Could you try adding `alwayslink = True` to ~line 67 of third_party/wpilib/BUILD (should be within the wpiutil cc import target)?  This should be getting linked correctly but it's possible that something weird is happening there.

**Comment by camearle20** [comment]
I played with this a bit more and this is actually an issue with the binaries we use from WPILib which are compiled with GCC and have cxx11 ABI tagged name mangling:

```
cameron@CE-T14:~/Desktop/akit_pdp$ nm -gD external/wpilib_wpiutil_linux_x64_files/linux/x86-64/shared/libwpiutil.so  | grep StackTrace
0000000000074560 T _ZN3wpi13GetStackTraceB5cxx11Ei
00000000001544c0 T _ZN3wpi20GetStackTraceDefaultB5cxx11Ei
00000000000745a0 T _ZN3wpi20SetGetStackTraceImplEPFNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiE
```

We use a (sort of) hermetic clang toolchain on Linux and macOS which doesn't appear to be picking this up correctly.  The quick fix to this in the interest of getting this feature done is to just forward declare the needed wpiutil function with an abi-tag as opposed to including the header:

conduit/wpilibio/src/pdp_reader.h
```cpp
#include "conduit/wpilibio/include/pdp_reader.h"

#include <hal/PowerDistribution.h>
#include <hal/HALBase.h>
#include <hal/DriverStation.h>

#include <chrono>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <mutex>

namespace wpi {
  __attribute__((abi_tag("cxx11")))
  std::string GetStackTrace(int offset);
}
...
```

The better fix is to figure out how to make clang behave with these prebuilt artifacts (though this would likely not be an issue when building for the RIO since the athena toolchain is GCC) and the actual fix is that the repo refactoring we are working on will just build all of this from source anyway so clang will be compiling it all.

**Comment by camearle20** [comment]
Actually, just kidding! I will push a much better fix to this to main and you can pull that in

**Comment by camearle20** [comment]
> I haven't implemented a means to set the PDP module ID + type, but I'm open to recommendations on how that should be implemented.

I talked to Jonah about this and it seems like what we ideally want is to disable PDP autologging by default (it absolutely tanks performance when testing on a RIO without a PDP connected, though the separate thread may alleviate that). For setting the module type, adding a new JNI call is completely fine. The goal is just to avoid a ton of JNI calls that exchange a lot of data and would be running frequently in the robot loop. Since setting this is something that happens at startup we don't really care about that as much

**Comment by jlmcmchl** [comment]
I should have resolved your concern with this last commit - users would need to construct a PDP or a LoggedPDP instance in order to begin logging. This assumes that any one time there is only one PDP handle living on the rio, but I think that's a safe assumption to make here.

Also - I've discovered the can frame definitions in wpilib - and found a lot of calls that would occur are pretty unnecessary. I've included the necessary type definitions and parsers for the CAN frames, and constructed them by using the HAL CAN api. This has been verified with my CTRE PDP I have here, but I won't be able to test REV PDH frames here,

Also - this new implementation only works for real robot use. I think this is mostly fine, but we can easily fall back to the PDP HAL api for sim data. I'll implement that sometime in the next couple days.

**Comment by camearle20** [comment]
@jonahb55 could you test this on the PDH at some point this week?

**Comment by jonahb55** [comment]
I'll test the PDH support when I get a chance. I also have a couple of minor feature suggestions:

- It would be nice to log the RIO rail status along with the other SS data (at least fault count and enabled, maybe voltage and current too). We discovered after some recent problems with shorting that the rail status can be very useful for debugging.
- Since we already have a shim for `RobotController`, I think we should read the battery voltage and brownout status from `LoggedSystemStats` so that the data is updated during replay. I think we just never got around to setting that up before, and it's a little odd now to shim the CAN status but not the battery voltage/brownout status. If we add the rail status to conduit/SS, we might as well shim those methods too.

**Comment by jlmcmchl** [comment]
Shims + everything should be all set for systemstats / RobotController now. Running on real hardware and everything appears to be in order:
image

**Comment by jonahb55** [comment]
I tested this against a real PDH a few days ago. Reading the CAN frames was working fine, and I made a few other miscellaneous changes.

* I switch the system stats read to happen synchronously when the data is captured since there aren't periodic updates to match. Waiting for the DS packet meant that nothing was updated before the DS connects, which isn't ideal. I didn't observe any performance difference between this method and running it in a thread.
* Unrelated to the PD and SS changes, I found that waiting for packets in the DS reader thread causes some weird behavior when the DS disconnects. If the robot was enabled when it disconnects, the "DS attached" field in the control word never goes to false and so the user code think it's still enabled (WPILib's `DriverStation` class checks both the "enabled" and "DS attached" fields for this). I switched the control word to be read synchronously like the SS data, and then the HAL automatically sets DS attached to false a few seconds after disconnecting.
* I added the `fromLog` implementations to `LoggedSystemStats` and `LoggedPowerDistribution`. The only reason we skipped those originally was because the replayed data wouldn't be used anywhere. Now that we have the shimmed `PowerDistribution` and `RobotController` classes, we might as well make that data available in replay. I set up epoch time, faults, and sticky faults to log as int32s as a placeholder. Several of the loggable types will change with the move to WPILOG, including replacing int32 with int64 (WPILOG doesn't include int32 as one of the default types). Once that change is merged, we can log those values properly as int64s.
* I added logging calls to record the duration of the conduit capture in `Logger`. This seems useful for profiling now that more of the reads are happening synchronously.
* For a while I thought there was a bug with the PD logging because I couldn't see any values being logged. I eventually found it was actually a bug with the junction `LogTable` implementation, which doesn't clone logged arrays. The `LoggedPowerDistribution` implementation mutates the `pdpChannelCurrents` array rather than replacing it, so when the logger tried to compare changes between cycles it was operating on two references to the same object. I fixed it by switching the `LogTable` implementation to clone all logged arrays using `System.arraycopy`.

Are there further changes you're working on? If not, I think we can get this merged shortly.

**Comment by jlmcmchl** [comment]
Thanks for taking some time to test this. About a week ago I was playing around with the CAN Stream API, to see if it would be of any use here with the non-deterministic nature of CAN messages, but the performance gain was minimal. It did grant us a distinct advantage of capturing _any_ power distribution CAN messages, since we can setup a mask to capture all power distribution traffic. While that would be a nice feature, it didn't seem like it was worth the possible confusion if someone were to use this w/ multiple PDPs at once. I think we would rather provide consistent data for one PD device rather than incorrect data that could be coming from one of many PD devices.

Instead, in another effort to simplify the implementation, I repeated your work on system stats here - performance difference seems to be negligible, I couldn't notice a significant difference between synchronous CAN parsing and threaded parsing - after leaving my RIO running for a minute or so they both seem to hang around 2ms per loop. It might be 0.5 - 1ms slower to parse PDP data in the regular loop, but it's hard to tell. Either way, this should be straightforward to add a loop in in the future.

**Pull request merged**
